language: groovy
jdk:
  - openjdk7
sudo: false
branches:
  only:
  - master
before_install:
  - wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
  - chmod +x ala_common.sh
  - source ./ala_common.sh
  - ala_travis_grails_setup_env

script:
  - ala_travis_grails_build

env:
  global:
  - secure: dEUGIV/VsORNT9kwqW3I7MOcA73cCQ6rD7QSJZCLcWSjZgiOxzuj0VWXw8d1hr8pO8Vq0ZEmy1FKvUQvLK40Xmx4OEIahcxRSe+mNH7UkaGYQsU2cjBt3TjFenVvhJbeAXPRWk21PlAoVtCyoROOV1o9h+ju+iWyb3IQpVil+Hw=
  - secure: TVqWHrvy/myQ16dnZT78eryZqbkmStOPMlxUNt8i4a/oa5EbbAssWsDT8NQODG+yY2HAhlPpS5BX9qhndSZ8MHAbDK1a7wvBKaBqxnCXiCQpXq9rZT9k5SB3BXUX/UrxKX7G6clWveQVBqqSdixA6H1dusksEObv76G5bgbT6tk=
